# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('type', models.CharField(choices=[('IN', 'Instructions'), ('MC', 'Multichoice'), ('ES', 'Essay'), ('AN', 'Anonymous')], max_length=15)),
                ('timed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
    ]
