# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20171116_2217'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('activity', 'number')]),
        ),
    ]
