# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20171117_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['activity', 'number']},
        ),
    ]
