# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20171117_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['number']},
        ),
    ]
