# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20171117_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('IN', 'Instructions'), ('MC', 'Multichoice'), ('ES', 'Essay'), ('AN', 'Anonymous'), ('CO', 'Table of Contents')], max_length=15),
        ),
    ]
