# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_userresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='action',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Action'),
        ),
    ]
